# Generated by Django 5.0 on 2024-12-30 17:57

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AccountUsername', models.CharField(max_length=255, unique=True)),
                ('AccountPassword', models.CharField(max_length=255)),
                ('AccountEmail', models.CharField(max_length=255, unique=True)),
                ('AccountNip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAccount',
            fields=[
                ('ProfileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProfileName', models.CharField(max_length=255)),
                ('ProfileLastname', models.CharField(max_length=255)),
                ('ProfileNumberphone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ProfileAccountid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appAccounts.account')),
            ],
        ),
    ]
