# Generated by Django 5.0 on 2025-01-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('accountid', models.BigAutoField(primary_key=True, serialize=False)),
                ('accountusername', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('accountnip', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='ProfileAccount',
            fields=[
                ('profileid', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilename', models.CharField(max_length=255)),
                ('profilelastname', models.CharField(max_length=255)),
                ('profilenumberphone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profileaccountid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_account',
            },
        ),
    ]
