<<<<<<< HEAD
# Generated by Django 5.0 on 2024-12-30 17:57

import django.db.models.deletion
=======
# Generated by Django 5.1.4 on 2024-12-30 03:46

>>>>>>> 799dbc47461350514c047e96c2008c2519d0ba25
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Account',
            fields=[
                ('AccountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AccountUsername', models.CharField(max_length=255, unique=True)),
                ('AccountPassword', models.CharField(max_length=255)),
                ('AccountEmail', models.CharField(max_length=255, unique=True)),
                ('AccountNip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAccount',
            fields=[
                ('ProfileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProfileName', models.CharField(max_length=255)),
                ('ProfileLastname', models.CharField(max_length=255)),
                ('ProfileNumberphone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ProfileAccountid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appAccounts.account')),
            ],
=======
            name='Accounts',
            fields=[
                ('accountid', models.BigAutoField(primary_key=True, serialize=False)),
                ('accountusername', models.CharField(max_length=255, unique=True)),
                ('accountpassword', models.CharField(max_length=255)),
                ('accountemail', models.CharField(max_length=255, unique=True)),
                ('accountnip', models.IntegerField()),
            ],
            options={
                'db_table': 'Accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditlogs',
            fields=[
                ('auditlogid', models.BigAutoField(primary_key=True, serialize=False)),
                ('auditlogdescription', models.TextField()),
                ('auditlogtime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AuditLogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('coinidbig', models.AutoField(primary_key=True, serialize=False)),
                ('coinname', models.CharField(max_length=100)),
                ('coinkey', models.CharField(max_length=5)),
                ('coinimgpath', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('coinvalue', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Coins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profileaccounts',
            fields=[
                ('profileid', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilename', models.CharField(max_length=255)),
                ('profilelastname', models.CharField(max_length=255)),
                ('profilenumberphone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'ProfileAccounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('transactionamount', models.BigIntegerField()),
                ('transactiondate', models.TimeField()),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletid', models.BigAutoField(primary_key=True, serialize=False)),
                ('walletbalance', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Wallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Walletcoins',
            fields=[
                ('walletcoinid', models.BigAutoField(primary_key=True, serialize=False)),
                ('walletcoinquantity', models.BigIntegerField()),
            ],
            options={
                'db_table': 'WalletCoins',
                'managed': False,
            },
>>>>>>> 799dbc47461350514c047e96c2008c2519d0ba25
        ),
    ]
