# Generated by Django 5.0 on 2025-01-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountnip',
            field=models.IntegerField(null=True),
        ),
    ]
