# Generated by Django 5.0 on 2025-01-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='appaccounts_account',
        ),
    ]
