# Generated by Django 5.0 on 2025-01-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0002_alter_account_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='AccountEmail',
            new_name='Accountemail',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='AccountID',
            new_name='Accountid',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='AccountNip',
            new_name='Accountnip',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='AccountPassword',
            new_name='Accountpassword',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='AccountUsername',
            new_name='Accountusername',
        ),
    ]
