# Generated by Django 5.0 on 2025-01-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0003_rename_accountemail_account_accountemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Accountemail',
            new_name='accountemail',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Accountid',
            new_name='accountid',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Accountnip',
            new_name='accountnip',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Accountpassword',
            new_name='accountpassword',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Accountusername',
            new_name='accountusername',
        ),
    ]
