# Generated by Django 5.0 on 2025-01-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0008_rename_accountemail_account_accountemail_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
