# Generated by Django 5.0 on 2025-01-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0009_alter_account_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileaccount',
            old_name='ProfileAccountid',
            new_name='profileaccountid',
        ),
        migrations.RenameField(
            model_name='profileaccount',
            old_name='ProfileID',
            new_name='profileid',
        ),
        migrations.RenameField(
            model_name='profileaccount',
            old_name='ProfileLastname',
            new_name='profilelastname',
        ),
        migrations.RenameField(
            model_name='profileaccount',
            old_name='ProfileName',
            new_name='profilename',
        ),
        migrations.RenameField(
            model_name='profileaccount',
            old_name='ProfileNumberphone',
            new_name='profilenumberphone',
        ),
    ]
