# Generated by Django 5.0 on 2025-01-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0010_rename_profileaccountid_profileaccount_profileaccountid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
