# Generated by Django 5.0 on 2025-01-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0011_alter_account_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profileaccount',
            table='profile_account',
        ),
    ]
