# Generated by Django 5.0 on 2024-12-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('AuditlogID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AuditlogDescription', models.TextField()),
                ('AuditlogTime', models.DateTimeField(blank=True, null=True)),
                ('AuditlogAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appAccounts.account')),
            ],
        ),
    ]
