# Generated by Django 5.0 on 2025-01-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('auditid', models.IntegerField(primary_key=True, serialize=False)),
                ('auditname', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'audit_type',
            },
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('auditlogid', models.BigAutoField(primary_key=True, serialize=False)),
                ('auditlogdescription', models.TextField()),
                ('auditlogtime', models.DateTimeField(blank=True, null=True)),
                ('auditlogaccountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('audittypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLogs.audittype')),
            ],
            options={
                'db_table': 'auditlog',
            },
        ),
    ]
