# Generated by Django 5.1.4 on 2025-01-04 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('AuditlogID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AuditlogDescription', models.TextField()),
                ('AuditlogTime', models.DateTimeField(blank=True, null=True)),
                ('AuditlogAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
