# Generated by Django 5.0 on 2025-01-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
        ('appLogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='AuditlogAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAccounts.account'),
        ),
    ]
