# Generated by Django 5.0 on 2025-01-11 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLogs', '0002_alter_auditlog_auditlogaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('auditid', models.IntegerField(primary_key=True, serialize=False)),
                ('auditname', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='AuditlogAccount',
            new_name='auditlogaccountid',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='AuditlogDescription',
            new_name='auditlogdescription',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='AuditlogID',
            new_name='auditlogid',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='AuditlogTime',
            new_name='auditlogtime',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='audittypeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appLogs.audittype'),
            preserve_default=False,
        ),
    ]
