# Generated by Django 5.0 on 2025-01-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLogs', '0003_audittype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='auditlog',
        ),
        migrations.AlterModelTable(
            name='audittype',
            table='audit_type',
        ),
    ]
