# Generated by Django 5.1.4 on 2025-01-04 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('AccountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AccountUsername', models.CharField(max_length=255, null=True, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('AccountNip', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileAccount',
            fields=[
                ('ProfileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProfileName', models.CharField(max_length=255)),
                ('ProfileLastname', models.CharField(max_length=255)),
                ('ProfileNumberphone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ProfileAccountid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
