# Generated by Django 5.0 on 2024-12-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TransactionAmount', models.BigIntegerField()),
                ('TransactionDate', models.DateTimeField()),
                ('TransactionReceiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='appAccounts.account')),
                ('TransactionTransmitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter', to='appAccounts.account')),
            ],
        ),
    ]
