# Generated by Django 5.0 on 2025-01-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appWallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('transactionstatusid', models.IntegerField(primary_key=True, serialize=False)),
                ('transactionstatus', models.CharField()),
            ],
            options={
                'db_table': 'transaction_status',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('transactionamount', models.DecimalField(decimal_places=20, max_digits=100)),
                ('transactiondate', models.DateTimeField()),
                ('transactioncoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWallets.coin')),
                ('transactionreceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('transactiontransmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter', to=settings.AUTH_USER_MODEL)),
                ('transactionstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTransactions.transactionstatus')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
