# Generated by Django 5.0 on 2024-12-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
        ('appTransactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
