# Generated by Django 5.0 on 2025-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionamount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
