# Generated by Django 5.0 on 2025-01-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTransactions', '0003_alter_transaction_transactionreceiver_and_more'),
        ('appWallets', '0006_alter_wallet_walletaccountsid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='TransactionCoin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appWallets.coin'),
            preserve_default=False,
        ),
    ]
