# Generated by Django 5.0 on 2025-01-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTransactions', '0005_rename_transactioncoin_transaction_transactioncoin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('transactionstatusid', models.IntegerField(primary_key=True, serialize=False)),
                ('transactionstatus', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appTransactions.transactionstatus'),
            preserve_default=False,
        ),
    ]
