# Generated by Django 5.0 on 2025-01-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTransactions', '0006_transactionstatus_transaction_transactionstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='transactionstatus',
            table='transaction_status',
        ),
    ]
