# Generated by Django 5.0 on 2025-01-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTransactions', '0007_alter_transaction_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionamount',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
