# Generated by Django 5.0 on 2025-01-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_contacts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact',
                'unique_together': {('owner', 'contact_user')},
            },
        ),
    ]
