# Generated by Django 5.0 on 2025-01-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coinid', models.BigAutoField(primary_key=True, serialize=False)),
                ('coinname', models.CharField(max_length=100)),
                ('coinkey', models.CharField(max_length=5)),
                ('coinimgpath', models.ImageField(blank=True, null=True, unique=True, upload_to='coins/')),
                ('coinvalue', models.DecimalField(decimal_places=15, max_digits=100)),
            ],
            options={
                'db_table': 'coin',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletid', models.BigAutoField(primary_key=True, serialize=False)),
                ('walletbalance', models.DecimalField(decimal_places=20, max_digits=100)),
                ('walletaccountsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walletcoinsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWallets.coin')),
                ('walletcoinquantity', models.DecimalField(decimal_places=20, max_digits=100)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
    ]
