# Generated by Django 5.0 on 2024-12-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('CoinID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CoinName', models.CharField(max_length=100)),
                ('CoinKey', models.CharField(max_length=5)),
                ('CoinImgPath', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('CoinValue', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('WalletID', models.BigAutoField(primary_key=True, serialize=False)),
                ('WalletBalance', models.BigIntegerField()),
                ('WalletAccountsID', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletCoins',
            fields=[
                ('WalletCoindID', models.BigAutoField(primary_key=True, serialize=False)),
                ('WalletCoinQuantity', models.BigIntegerField()),
                ('WalletCoinWalletID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appWallets.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='WalletCoinsID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appWallets.walletcoins'),
        ),
    ]
