# Generated by Django 5.1.4 on 2025-01-04 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('CoinID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CoinName', models.CharField(max_length=100)),
                ('CoinKey', models.CharField(max_length=5)),
                ('CoinImgPath', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('CoinValue', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('WalletID', models.BigAutoField(primary_key=True, serialize=False)),
                ('WalletCoinQuantity', models.BigIntegerField()),
                ('WalletBalance', models.BigIntegerField()),
                ('WalletAccountsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('WalletCoinsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWallets.coin')),
            ],
        ),
    ]
