# Generated by Django 5.0 on 2024-12-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletCoins',
            new_name='WalletCoin',
        ),
    ]
