# Generated by Django 5.0 on 2025-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinvalue',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='walletbalance',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='walletcoinquantity',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
