# Generated by Django 5.0 on 2025-01-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0002_alter_coin_coinvalue_alter_wallet_walletbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinkey',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
