# Generated by Django 5.0 on 2024-12-29 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0003_rename_walletcoindid_walletcoin_walletcoinid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='WalletCoinsID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appWallets.coin'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='WalletCoinQuantity',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='WalletAccountsID',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='WalletCoin',
        ),
    ]
