# Generated by Django 5.0 on 2024-12-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
        ('appWallets', '0004_alter_wallet_walletcoinsid_wallet_walletcoinquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='WalletAccountsID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appAccounts.account'),
        ),
    ]
