# Generated by Django 5.0 on 2025-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0006_alter_wallet_walletaccountsid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='CoinImgPath',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='coins/'),
        ),
    ]
