# Generated by Django 5.0 on 2025-01-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0007_alter_coin_coinimgpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='CoinID',
            new_name='coinid',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='CoinImgPath',
            new_name='coinimgpath',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='CoinKey',
            new_name='coinkey',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='CoinName',
            new_name='coinname',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='CoinValue',
            new_name='coinvalue',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='WalletAccountsID',
            new_name='walletaccountsid',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='WalletBalance',
            new_name='walletbalance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='WalletCoinQuantity',
            new_name='walletcoinQuantity',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='WalletCoinsID',
            new_name='walletcoinsid',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='WalletID',
            new_name='walletid',
        ),
    ]
