# Generated by Django 5.0 on 2025-01-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0008_rename_coinid_coin_coinid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coin',
            table='coin',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='wallet',
        ),
    ]
