# Generated by Django 5.0 on 2025-01-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0009_alter_coin_table_alter_wallet_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinvalue',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
    ]
