# Generated by Django 5.0 on 2025-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0011_alter_coin_coinvalue_alter_wallet_walletbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinvalue',
            field=models.DecimalField(decimal_places=15, max_digits=100),
        ),
    ]
