# Generated by Django 5.0 on 2025-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWallets', '0012_alter_coin_coinvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='walletcoinQuantity',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
